title: "Photo Stream"
description: "Super simple photo stream, powered by Cecil"
baseurl: "https://photo-stream.cecil.app/"
author:
  name: Unsplash
  url: https://unsplash.com/s/photos/open-source
output:
  pagetypeformats:
    homepage: html
defaultpages:
  sitemap:
    published: false
static:
  load: true
cache:
  enabled: true
postprocess:
  enabled: true
