title: "Unsplash Photo Stream"
description: "Super simple Photo Stream, powered by Cecil."
baseurl: "https://photo-stream.cecil.app/"
author:
  name: Unsplash
  url: https://unsplash.com/s/photos/open-source
output:
  pagetypeformats:
    homepage: html
defaultpages:
  sitemap:
    published: false
static:
  load: true
metatags:
  jsonld:
    enabled: true
assets:
  images:
    optimize:
      enabled: true
    responsive:
      enabled: true
    webp:
      enabled: true
