title: "Photo Stream demo"
description: "Super simple photo stream, powered by Unsplash & Cecil."
baseurl: https://photo-stream-demo.cecil.app/
author:
  name: Unsplash
  url: https://unsplash.com/s/photos/open-source

photo:
  style:
    color:
      background: "black"
      text: "white"
    img:
      height: 300px
      margin: 2px
  sort: asc
  size:
    thumbnail: 640
    full: 1920
  placeholder: image # image, color or false

output:
  pagetypeformats:
    homepage: html
defaultpages:
  sitemap:
    published: false
  xsl/atom:
    published: false
  xsl/rss:
    published: false
static:
  load: true
metatags:
  jsonld:
    enabled: true
assets:
  images:
    optimize:
      enabled: true
    quality: 75
    responsive:
      enabled: true
    webp:
      enabled: true
