title: "Photo Stream demo"
description: "Super simple photo stream, powered by Unsplash & Cecil."
baseurl: https://photo-stream-demo.cecil.app/
author:
  name: Unsplash
  url: https://unsplash.com/s/photos/open-source

output:
  pagetypeformats:
    homepage: html
defaultpages:
  sitemap:
    published: false
  xsl/atom:
    published: false
  xsl/rss:
    published: false
static:
  load: true
metatags:
  jsonld:
    enabled: true
assets:
  images:
    optimize:
      enabled: true
    responsive:
      enabled: true
    webp:
      enabled: true
