title: "Photo Stream"
description: "Super simple photo stream, powered by Cecil"
baseurl: "/"
author:
  name: Unsplash
  url: https://unsplash.com/s/photos/open-source
static:
  load: true
cache:
  enabled: true
optimize:
  enabled: true
